spring.application.name=EmergencyMM

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DBEmergencyMM;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration